// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RizSoft.Acme.Domain.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderRows = new HashSet<OrderRow>();
        }

        public int Id { get; set; }
        public DateTime OrderDate { get; set; }
        public int CustomerId { get; set; }
        public decimal? ShippingCosts { get; set; }
        public bool Processed { get; set; }
        public DateTime? ShippedDate { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderRow> OrderRows { get; set; }
    }
}