// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RizSoft.Acme.Domain.Models
{
    public partial class Product
    {
        public Product()
        {
            TagsProducts = new HashSet<TagsProduct>();
        }

        public int Id { get; set; }
        public string Sku { get; set; }
        public string ProductName { get; set; }
        /// <summary>
        /// 1=Product, 2=Service, 3=Digital
        /// </summary>
        public byte ProductType { get; set; }
        public int? CategoryId { get; set; }
        public decimal ListPrice { get; set; }
        public bool Discontinued { get; set; }
        public decimal Weight { get; set; }
        public int PackDimension { get; set; }
        /// <summary>
        /// L=LIFO, F=FIFO
        /// </summary>
        public string CostingMethod { get; set; }
        public DateTime OnMarketSince { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string DataSheetUrl { get; set; }
        public Guid? RowGuid { get; set; }
        public byte[] RowTimestamp { get; set; }
        public DateTime? LastModifiedDate { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<TagsProduct> TagsProducts { get; set; }
    }
}