// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RizSoft.Acme.Domain.Models
{
    public partial class Tag
    {
        public Tag()
        {
            Products = new HashSet<Product>();
        }

        public int Id { get; set; }
        public string TagName { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}